<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.tinysc</groupId>
        <artifactId>tinysc-parent</artifactId>
        <version>1.0.0-alpha-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>tinysc-integration-tests</artifactId>
    <name>tinysc :: integration tests</name>

    <dependencies>
        <dependency>
            <groupId>io.tinysc</groupId>
            <artifactId>tinysc-launcher</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.tinysc</groupId>
            <artifactId>tinysc-testapp-javax</artifactId>
            <version>${project.version}</version>
            <type>war</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <tinysc.launcher.jar>${maven.multiModuleProjectDirectory}/src/tinysc-launcher/target/tinysc-${project.version}.jar</tinysc.launcher.jar>
                        <tinysc.probe.war>${maven.multiModuleProjectDirectory}/src/tinysc-testapp-javax/target/probe-javax31.war</tinysc.probe.war>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
